services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_service
      - book_service_1
      - book_service_2
      - borrow_service
    networks:
      - library-network

  auth_service:
    image: mengkheangseng99/auth-service
    build:
      context: .
      dockerfile: Auth_service/Dockerfile
    environment:
      - MONGO_URI=${AUTH_MONGO_URI}
      - JWT_SECRET=${JWT_SECRETE}
    networks:
      - library-network

  book_service_1:
    image: mengkheangseng99/book-service
    build:
      context: .
      dockerfile: Book_service/Dockerfile
    environment:
      - MONGO_URI=${BOOK_MONGO_URI}
      - JWT_SECRET=${JWT_SECRETE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - library-network

  book_service_2:
    image: mengkheangseng99/book-service
    build:
      context: .
      dockerfile: Book_service/Dockerfile
    environment:
      - MONGO_URI=${BOOK_MONGO_URI}
      - JWT_SECRET=${JWT_SECRETE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - library-network

  borrow_service:
    image: mengkheangseng99/borrow-service
    build:
      context: .
      dockerfile: Borrow_service/Dockerfile
    environment:
      - MONGO_URI=${BORROW_MONGO_URI}
      - JWT_SECRET=${JWT_SECRETE}
      - BOOK_SERVICE_URL=http://nginx/books
    depends_on:
      - book_service_1
      - book_service_2
    networks:
      - library-network

  redis:
    image: redis:latest
    networks:
      - library-network

networks:
  library-network:
    driver: bridge