events {
  worker_connections 1024;
}

http {
  # load balance book service only
  upstream book_service {
    server book_service_1:3001;
    server book_service_2:3001;
  }

  server {
    listen 80;

    # auth — bypass API Gateway, no token needed
    location /auth {
      proxy_pass http://auth_service:3000;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # books — load balanced between instances
    location /books {
      proxy_pass http://book_service;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # borrow — single service
    location /borrow {
      proxy_pass http://borrow_service:3002;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}