events {
  worker_connections 1024;
}

http {
  upstream book_service {
    server book_service_1:3001;
    server book_service_2:3001;
  }

  server {
    listen 8080;

    location /books {
      proxy_pass http://book_service;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}

