apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-sys-api-gateway
  namespace: library-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-sys-api-gateway
  template:
    metadata:
      labels:
        app: library-sys-api-gateway
    spec:
      containers:
        - name: library-sys-api-gateway
          image: sovanda07/library-sys-api-gateway:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: library-config
            - secretRef:
                name: library-secrets
          env:
            - name: PORT
              value: "4000"
          volumeMounts:
            - name: shared-logs
              mountPath: /shared/logs
        - name: shared-logger
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /shared/logs
              for i in 1 2 3; do echo "api-gateway: $(date)" >> /shared/logs/api.txt && break || sleep 1; done
              sleep 3600
          volumeMounts:
            - name: shared-logs
              mountPath: /shared/logs
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: library-sys-shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: library-sys-api-gateway
  namespace: library-system
spec:
  type: LoadBalancer
  selector:
    app: library-sys-api-gateway
  ports:
    - port: 4000
      targetPort: 4000
