apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-sys-borrow-service
  namespace: library-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-sys-borrow-service
  template:
    metadata:
      labels:
        app: library-sys-borrow-service
    spec:
      containers:
        - name: library-sys-borrow-service
          image: sovanda07/library-sys-borrow-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: library-config
            - secretRef:
                name: library-secrets
          env:
            - name: PORT
              value: "3002"
---
apiVersion: v1
kind: Service
metadata:
  name: library-sys-borrow-service
  namespace: library-system
spec:
  selector:
    app: library-sys-borrow-service
  ports:
    - port: 3002
      targetPort: 3002
