apiVersion: v1
kind: Secret
metadata:
  name: library-secrets
  namespace: library-system
type: Opaque
stringData:
  JWT_SECRET: "my_secret_key"
  MONGO_URI: "mongodb://sovanda:SNb6pPs52D1ow8gh@ac-z3r3tb8-shard-00-00.pfat8fm.mongodb.net:27017,ac-z3r3tb8-shard-00-01.pfat8fm.mongodb.net:27017,ac-z3r3tb8-shard-00-02.pfat8fm.mongodb.net:27017/?ssl=true&replicaSet=atlas-y6x4ca-shard-0&authSource=admin&appName=Library-System"
